# Generated by Django 5.2.4 on 2026-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenRegulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Almacén regulado',
                'verbose_name_plural': 'Almacenes regulados',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ExcursionBPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Excursión BPA',
                'verbose_name_plural': 'Excursiones BPA',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LoteBPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero_lote', models.CharField(max_length=120)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_regulatorio', models.CharField(choices=[('CUARENTENA', 'Cuarentena'), ('LIBERADO', 'Liberado'), ('OBSERVADO', 'Observado'), ('BLOQUEADO', 'Bloqueado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], default='CUARENTENA', max_length=30)),
                ('motivo_estado', models.TextField(blank=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='bpa/lotes/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Lote BPA',
                'verbose_name_plural': 'Lotes BPA',
                'ordering': ['producto', 'numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='ZonaRegulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('CUARENTENA', 'Cuarentena'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DEVOLUCION', 'Devolución'), ('OTRA', 'Otra')], max_length=30)),
            ],
            options={
                'verbose_name': 'Zona regulada',
                'verbose_name_plural': 'Zonas reguladas',
            },
        ),
    ]
