# Generated by Django 5.2.4 on 2026-06-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpa', '0001_initial'),
        ('core', '0001_initial'),
        ('qms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenregulado',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almacenes_bpa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursionbpa',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursiones', to='bpa.almacenregulado'),
        ),
        migrations.AddField(
            model_name='excursionbpa',
            name='desviacion_qms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursiones_bpa', to='qms.desviacion'),
        ),
        migrations.AddField(
            model_name='lotebpa',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bpa.almacenregulado'),
        ),
        migrations.AddField(
            model_name='lotebpa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_bpa', to='core.producto'),
        ),
        migrations.AddField(
            model_name='lotebpa',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_bpa_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursionbpa',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excursiones', to='bpa.lotebpa'),
        ),
        migrations.AddField(
            model_name='zonaregulada',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='bpa.almacenregulado'),
        ),
        migrations.AddField(
            model_name='lotebpa',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bpa.zonaregulada'),
        ),
        migrations.AlterUniqueTogether(
            name='zonaregulada',
            unique_together={('almacen', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='lotebpa',
            index=models.Index(fields=['numero_lote'], name='bpa_lotebpa_numero__e1e93a_idx'),
        ),
        migrations.AddIndex(
            model_name='lotebpa',
            index=models.Index(fields=['producto', 'numero_lote'], name='bpa_lotebpa_product_16bff2_idx'),
        ),
    ]
