# Generated by Django 5.2.4 on 2026-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Ingreso'), ('EXPORT', 'Exportar')], max_length=20)),
                ('modulo', models.CharField(max_length=40)),
                ('entidad', models.CharField(max_length=120)),
                ('entidad_id', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
