# Generated by Django 5.2.4 on 2026-06-03 06:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(blank=True, help_text='Ejemplo: Responsable, Asistente, Revisor, Aprobador, Auditor.', max_length=80)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre_comercial'], 'verbose_name': 'Producto legado de Core', 'verbose_name_plural': 'Productos legados de Core'},
        ),
        migrations.AddField(
            model_name='licenciamodulo',
            name='clave_local',
            field=models.CharField(blank=True, help_text='Clave o referencia local para instalaciones on-premise.', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Campo heredado. Usar cargo funcional para nuevas asignaciones.', max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo_funcional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.cargo'),
        ),
        migrations.CreateModel(
            name='RolFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=140)),
                ('nivel', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('ASISTENTE', 'Asistente'), ('REVISOR', 'Revisor'), ('APROBADOR', 'Aprobador'), ('AUDITOR', 'Auditor / Consulta'), ('ADMINISTRADOR', 'Administrador')], default='ASISTENTE', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('puede_cerrar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_funcionales', to='core.modulosistema')),
            ],
            options={
                'verbose_name': 'Rol funcional',
                'verbose_name_plural': 'Roles funcionales',
                'ordering': ['modulo__codigo', 'nivel', 'nombre'],
                'unique_together': {('modulo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='BitacoraAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.CharField(max_length=30)),
                ('accion', models.CharField(max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('resumen', models.TextField()),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de acción',
                'verbose_name_plural': 'Bitácora de acciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['modulo'], name='core_bitaco_modulo_7d5556_idx'), models.Index(fields=['accion'], name='core_bitaco_accion_52f06a_idx'), models.Index(fields=['creado_en'], name='core_bitaco_creado__3f5e5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_sigefar', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='core.rolfuncional')),
            ],
            options={
                'verbose_name': 'Asignación de rol',
                'verbose_name_plural': 'Asignaciones de roles',
                'ordering': ['usuario__username', 'rol__modulo__codigo'],
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
