# Generated by Django 5.2 on 2026-06-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo_sede', models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('REGULATORIA', 'Regulatoria'), ('COMERCIAL', 'Comercial'), ('OPERATIVA', 'Operativa no BPA'), ('OTRA', 'Otra')], default='ADMINISTRATIVA', max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('responsable_contacto', models.CharField(blank=True, max_length=180)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=40)),
                ('observaciones', models.TextField(blank=True, help_text='La sede de empresa no reemplaza almacenes regulados BPA.')),
            ],
            options={
                'verbose_name': 'Sede de empresa',
                'verbose_name_plural': 'Sedes de empresa',
                'ordering': ['empresa__razon_social', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dominio_sistema',
            field=models.CharField(blank=True, help_text='Dominio, IP o referencia interna donde opera SIGEFAR para esta empresa.', max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_operativo',
            field=models.CharField(choices=[('IMPLEMENTACION', 'En implementación'), ('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('INACTIVA', 'Inactiva')], default='IMPLEMENTACION', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_sistema',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('DROGUERIA', 'Droguería'), ('LABORATORIO', 'Laboratorio'), ('DISTRIBUIDORA', 'Distribuidora'), ('IMPORTADORA', 'Importadora'), ('TITULAR_RS', 'Titular de registro sanitario'), ('CONSULTORA', 'Consultora regulatoria'), ('OTRA', 'Otra')], default='DROGUERIA', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_instalacion',
            field=models.CharField(choices=[('LOCAL', 'Servidor local / red interna'), ('HOST_CLIENTE', 'Host propio del cliente'), ('VPS', 'VPS privado'), ('NUBE', 'Nube'), ('HIBRIDO', 'Híbrido')], default='HOST_CLIENTE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ruc'], name='core_empres_ruc_37d960_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['estado_operativo'], name='core_empres_estado__cb9921_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tipo_empresa'], name='core_empres_tipo_em_96ce0d_idx'),
        ),
        migrations.AddField(
            model_name='sedeempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='sedeempresa',
            index=models.Index(fields=['codigo'], name='core_sedeem_codigo_4f3edd_idx'),
        ),
        migrations.AddIndex(
            model_name='sedeempresa',
            index=models.Index(fields=['tipo_sede'], name='core_sedeem_tipo_se_4e948f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sedeempresa',
            unique_together={('empresa', 'codigo')},
        ),
    ]
