# Generated by Django 5.2 on 2026-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sedeempresa_empresa_ciudad_empresa_dominio_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedeempresa',
            name='observaciones',
            field=models.TextField(blank=True, help_text='En Core la sede es referencia base. El control regulado de almacenes BPA se gestiona en SIGEFAR-BPA.'),
        ),
        migrations.AlterField(
            model_name='sedeempresa',
            name='tipo_sede',
            field=models.CharField(choices=[('OFICINA_REGULATORIA', 'Oficina regulatoria'), ('ALMACEN', 'Almacén')], default='OFICINA_REGULATORIA', max_length=30),
        ),
    ]
