# Generated by Django 5.2.4 on 2026-06-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desviacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('origen', models.CharField(choices=[('QMS', 'Calidad'), ('BPA', 'BPA'), ('BPDT', 'BPDT'), ('BPFV', 'BPFV')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('INVESTIGACION', 'En investigación'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desviaciones_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desviación',
                'verbose_name_plural': 'Desviaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('VERIFICACION', 'Verificación de eficacia'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('verificacion_eficacia', models.TextField(blank=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_responsable', to=settings.AUTH_USER_MODEL)),
                ('desviacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capas', to='qms.desviacion')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPA',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoControlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='qms/documentos/%Y/%m/')),
                ('historial_cambios', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento controlado',
                'verbose_name_plural': 'Documentos controlados',
                'ordering': ['codigo', 'version'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero_registro', models.CharField(max_length=120, unique=True)),
                ('titular', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('documento_controlado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qms.documentocontrolado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_sanitarios', to='core.producto')),
            ],
            options={
                'verbose_name': 'Registro sanitario',
                'verbose_name_plural': 'Registros sanitarios',
                'ordering': ['producto', 'numero_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRegulatorioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('FICHA_TECNICA', 'Ficha técnica'), ('INSERTO', 'Inserto'), ('ROTULADO', 'Rotulado'), ('CONDICION_ALMACENAMIENTO', 'Condición aprobada de almacenamiento'), ('CONDICION_TRANSPORTE', 'Condición aprobada de transporte')], max_length=40)),
                ('documento_controlado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qms.documentocontrolado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_regulatorios', to='core.producto')),
            ],
            options={
                'verbose_name': 'Documento regulatorio de producto',
                'verbose_name_plural': 'Documentos regulatorios de producto',
                'unique_together': {('producto', 'tipo', 'documento_controlado')},
            },
        ),
    ]
