# Generated by Django 5.2.4 on 2026-06-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
        ('regulatorio', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosanitario',
            name='documento_controlado',
        ),
        migrations.RemoveField(
            model_name='registrosanitario',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='documentocontrolado',
            options={'ordering': ['codigo', 'version'], 'verbose_name': 'Documento del SGI', 'verbose_name_plural': 'Documentos del SGI'},
        ),
        migrations.RemoveField(
            model_name='desviacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='desviacion',
            name='producto_regulatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desviaciones_qms', to='regulatorio.productoregulatorio'),
        ),
        migrations.AddField(
            model_name='documentocontrolado',
            name='tipo_sgi',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PROCEDIMIENTO', 'Procedimiento'), ('INSTRUCTIVO', 'Instructivo'), ('FORMATO', 'Formato'), ('REGISTRO_INTERNO', 'Registro interno'), ('PROGRAMA', 'Programa'), ('PLAN', 'Plan'), ('MATRIZ', 'Matriz'), ('POLITICA', 'Política'), ('OTRO_SGI', 'Otro documento SGI')], default='PROCEDIMIENTO', max_length=40),
        ),
        migrations.AlterField(
            model_name='desviacion',
            name='origen',
            field=models.CharField(choices=[('QMS', 'Calidad'), ('REG', 'Regulatorio'), ('BPA', 'BPA'), ('BPDT', 'BPDT'), ('BPFV', 'BPFV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='qms/documentos_sgi/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='DocumentoRegulatorioProducto',
        ),
        migrations.DeleteModel(
            name='RegistroSanitario',
        ),
    ]
