VISIBLE_MODULES = [
    {
        "slug": "core",
        "codigo": "CORE",
        "nombre": "SIGEFAR-Core",
        "titulo": "Núcleo común de la plataforma",
        "descripcion": "Administra empresas, usuarios, cargos, roles, permisos, autenticación, seguridad, bitácora, licenciamiento, adjuntos, notificaciones y parámetros generales.",
        "mensaje": "Core sostiene la suite y provee servicios transversales, sin administrar productos regulatorios, documentos regulatorios, CAPA, lotes ni procesos operativos.",
        "etiqueta": "Núcleo común",
        "icono": "◆",
        "componentes": ["Empresas y usuarios", "Cargos y perfiles", "Roles y permisos", "Seguridad", "Licenciamiento", "Parámetros", "Adjuntos", "Bitácora"],
        "principios": ["Sostiene la suite completa", "No se vende como módulo independiente", "No administra productos regulatorios", "Garantiza seguridad y trazabilidad transversal"],
    },
    {
        "slug": "regulatorio",
        "codigo": "REG",
        "nombre": "SIGEFAR-Regulatorio",
        "titulo": "Gestión regulatoria integral del producto",
        "descripcion": "Crea y gobierna el producto regulatorio, expedientes DIGEMID, registros sanitarios, trámites, observaciones, subsanaciones y documentos regulatorios del producto.",
        "mensaje": "Regulatorio es dueño funcional del producto regulatorio y de su ciclo de vida ante la autoridad sanitaria.",
        "etiqueta": "Módulo regulatorio",
        "icono": "◉",
        "componentes": ["Productos regulatorios", "Expedientes DIGEMID", "Registros sanitarios", "Trámites regulatorios", "Documentos regulatorios", "Observaciones", "Subsanaciones", "Alertas"],
        "principios": ["Crea y gobierna productos regulatorios", "Administra documentos regulatorios del producto", "Mantiene trazabilidad de expedientes y vencimientos", "Los demás módulos consultan productos según permisos"],
    },
    {
        "slug": "qms",
        "codigo": "QMS",
        "nombre": "SIGEFAR-Calidad",
        "titulo": "Sistema de Gestión Integrado y calidad",
        "descripcion": "Gestiona documentos del SGI, auditorías, hallazgos, desviaciones, CAPA, riesgos, cambios, capacitaciones, eficacia e indicadores de calidad.",
        "mensaje": "Calidad/QMS gobierna el Sistema de Gestión Integrado y toda CAPA, sin administrar productos ni documentos regulatorios del expediente.",
        "etiqueta": "Módulo rector",
        "icono": "✦",
        "componentes": ["Documentos del SGI", "Auditorías", "Hallazgos", "Desviaciones", "CAPA", "Riesgos", "Control de cambios", "Capacitaciones"],
        "principios": ["Gobierno del Sistema de Gestión Integrado", "CAPA única desde Calidad", "No administra documentos regulatorios del producto", "Mejora continua trazable"],
    },
    {
        "slug": "bpa",
        "codigo": "BPA",
        "nombre": "SIGEFAR-BPA",
        "titulo": "Buenas Prácticas de Almacenamiento",
        "descripcion": "Controla cumplimiento regulatorio del almacenamiento, condiciones ambientales, evidencias, excursiones y estados regulatorios de lotes.",
        "mensaje": "BPA controla almacenamiento regulatorio y lotes BPA sin convertirse en WMS ni inventario operativo.",
        "etiqueta": "Buenas prácticas",
        "icono": "▣",
        "componentes": ["Almacenes", "Zonas", "Lotes BPA", "Condiciones ambientales", "Excursiones", "Limpieza", "Plagas", "Equipos críticos"],
        "principios": ["No es WMS", "Consulta productos desde Regulatorio", "Deriva incumplimientos a Calidad", "Los lotes son transaccionales y regulatorios"],
    },
    {
        "slug": "bpdt",
        "codigo": "BPDT",
        "nombre": "SIGEFAR-BPDT",
        "titulo": "Buenas Prácticas de Distribución y Transporte",
        "descripcion": "Gestiona evidencia regulatoria del transporte, condiciones de conservación en tránsito, incidentes y devoluciones con impacto en calidad.",
        "mensaje": "BPDT controla distribución y transporte regulatorio sin convertirse en TMS ni sistema de planificación logística.",
        "etiqueta": "Buenas prácticas",
        "icono": "⬡",
        "componentes": ["Transportistas", "Vehículos", "Conductores", "Documentos de transporte", "Conservación", "Excursiones", "Incidentes", "Devoluciones"],
        "principios": ["No es TMS", "Consulta productos desde Regulatorio", "Controla evidencia regulatoria del transporte", "Deriva incumplimientos a Calidad"],
    },
    {
        "slug": "bpfv",
        "codigo": "BPFV",
        "nombre": "SIGEFAR-BPFV",
        "titulo": "Farmacovigilancia y BPFV",
        "descripcion": "Permite registrar, evaluar y dar seguimiento a casos de farmacovigilancia, vinculando productos regulatorios y lotes reportados cuando corresponda.",
        "mensaje": "BPFV gestiona farmacovigilancia y puede consultar lotes BPA vinculados sin modificar su estado regulatorio.",
        "etiqueta": "Farmacovigilancia",
        "icono": "✚",
        "componentes": ["Casos", "RAM", "Eventos adversos", "Errores de medicación", "Falta de eficacia", "Causalidad", "Seguimientos", "Reportes"],
        "principios": ["No administra productos regulatorios", "No modifica estados de lotes BPA", "Puede registrar lote no encontrado en BPA", "Escala hallazgos a Calidad cuando corresponda"],
    },
]

PRINCIPLES = [
    {"titulo": "Trazabilidad", "descripcion": "Toda acción relevante queda registrada para auditoría y revisión posterior.", "icono": "⌁"},
    {"titulo": "Gobierno documental distribuido", "descripcion": "Regulatorio gobierna documentos regulatorios del producto; QMS gobierna documentos del SGI.", "icono": "☷"},
    {"titulo": "Seguridad por roles", "descripcion": "Core controla identidad, acceso y permisos para que cada usuario vea solo lo autorizado.", "icono": "◉"},
    {"titulo": "Evidencia regulatoria", "descripcion": "Los registros sustentan trámites, auditorías, inspecciones y seguimiento interno.", "icono": "✓"},
]

FLOW_STEPS = [
    "Core sostiene usuarios, seguridad y licencias",
    "Regulatorio crea producto y expediente",
    "QMS gestiona SGI y CAPA",
    "BPA / BPDT / BPFV consultan producto regulatorio",
    "Hallazgos, incidentes o señales",
    "QMS verifica eficacia y cierre",
]


def sm(slug, nombre, descripcion, alcance, acciones, exclusiones, admin_url):
    return {"slug": slug, "nombre": nombre, "descripcion": descripcion, "alcance": alcance, "acciones": acciones, "exclusiones": exclusiones, "admin_url": admin_url}


SUBMODULES = {
    "core": [
        sm("empresas", "Empresas", "Registro de empresas usuarias de SIGEFAR Suite.", "Define la organización sobre la cual aplican usuarios, licencias y parámetros.", ["Crear empresa", "Editar datos", "Activar o inactivar", "Vincular usuarios"], ["No reemplaza ERP", "No administra productos", "No gobierna trámites"], "/admin/core/empresa/"),
        sm("usuarios-perfiles", "Usuarios y perfiles", "Gestión de usuarios, identidad, correo, estado y perfil organizacional.", "Administra usuarios como parte del núcleo común.", ["Crear usuario", "Editar perfil", "Activar o inactivar", "Asignar empresa"], ["No reemplaza RR.HH.", "No gestiona CAPA", "No administra expedientes"], "/admin/core/usuario/"),
        sm("cargos", "Cargos", "Catálogo de cargos funcionales de la organización.", "Permite diferenciar responsables, asistentes, revisores, aprobadores y auditores.", ["Crear cargo", "Definir nivel", "Asignar a usuario", "Mantener activo"], ["No define permisos por sí solo", "No reemplaza organigrama corporativo"], "/admin/core/cargo/"),
        sm("roles-permisos", "Roles y permisos", "Configuración de acceso por rol, funciones y visibilidad por módulo.", "Define qué puede ver y hacer cada usuario dentro de cada módulo.", ["Crear rol", "Definir permisos", "Restringir visibilidad", "Controlar acceso"], ["No administra documentos QMS", "No administra productos regulatorios"], "/admin/core/rolfuncional/"),
        sm("asignacion-roles", "Asignación múltiple de roles", "Permite que un usuario tenga más de un rol funcional.", "Un usuario puede operar como responsable en un módulo y consulta en otro.", ["Asignar rol", "Definir vigencia", "Registrar asignador", "Inactivar acceso"], ["No rompe segregación de funciones", "No otorga permisos fuera de licencia"], "/admin/core/asignacionrolusuario/"),
        sm("licenciamiento", "Licenciamiento modular", "Control de módulos habilitados por empresa.", "Permite activar módulos sin vender Core como módulo separado.", ["Habilitar módulo", "Definir vigencia", "Registrar clave local", "Controlar acceso"], ["Core no se vende solo", "No reemplaza contrato comercial"], "/admin/core/licenciamodulo/"),
        sm("parametros", "Parámetros generales", "Configuración transversal de comportamiento del sistema.", "Define reglas comunes sin duplicar lógica funcional de los módulos.", ["Crear parámetro", "Editar valor", "Documentar uso", "Auditar cambio"], ["No contiene datos regulatorios", "No reemplaza configuración del servidor"], "/admin/core/parametrogeneral/"),
        sm("adjuntos-notificaciones", "Adjuntos y notificaciones", "Servicios transversales de archivos y avisos.", "Core almacena infraestructura común, no gobierna el contenido funcional.", ["Subir adjunto", "Emitir aviso", "Marcar lectura", "Trazar origen"], ["No gobierna documentos regulatorios", "No gobierna documentos SGI"], "/admin/core/archivoadjunto/"),
        sm("bitacora", "Bitácora transversal", "Registro de acciones relevantes para auditoría.", "Permite revisar usuario, módulo, acción, objeto, resumen e IP de origen.", ["Consultar acción", "Filtrar módulo", "Revisar cambios", "Soportar auditoría"], ["No es expediente", "No reemplaza evidencia técnica adjunta"], "/admin/core/bitacoraaccion/"),
    ],
    "regulatorio": [
        sm("productos-regulatorios", "Productos regulatorios", "Creación y gobierno del producto regulado.", "Regulatorio es dueño funcional del producto regulatorio.", ["Crear producto", "Actualizar datos", "Controlar estado", "Consultar historial"], ["No crea lotes", "No gestiona CAPA"], "/admin/regulatorio/productoregulatorio/"),
        sm("expedientes-digemid", "Expedientes DIGEMID", "Control de expedientes ante la autoridad sanitaria.", "Gestiona trámite, etapa, autoridad, observaciones y resultado.", ["Crear expediente", "Registrar presentación", "Actualizar estado", "Registrar resolución"], ["No reemplaza portal de autoridad", "No cierra CAPA"], "/admin/regulatorio/expedientedigemid/"),
        sm("registros-sanitarios", "Registros sanitarios", "Control de número de registro, vigencia, estado y resolución.", "Mantiene trazabilidad del registro sanitario del producto.", ["Registrar número", "Controlar vencimiento", "Adjuntar resolución", "Actualizar estado"], ["No duplica producto en Core", "No administra documentos SGI"], "/admin/regulatorio/registrosanitarioregulatorio/"),
        sm("tramites", "Trámites regulatorios", "Gestión de inscripción, renovación, reinscripción y actualizaciones.", "Agrupa el ciclo de vida regulatorio del producto.", ["Clasificar trámite", "Definir responsable", "Controlar hitos", "Cerrar resultado"], ["No reemplaza mesa de partes", "No automatiza aprobación externa"], "/admin/regulatorio/expedientedigemid/"),
        sm("modificaciones-post-registro", "Modificaciones post-registro", "Control de cambios regulatorios aprobables ante autoridad.", "Registra modificaciones de titular, fabricante, presentación, rotulado, inserto o condiciones aprobadas.", ["Registrar cambio", "Vincular expediente", "Adjuntar sustento", "Actualizar historial"], ["No aprueba CAPA", "No modifica lotes BPA"], "/admin/regulatorio/expedientedigemid/"),
        sm("documentos-regulatorios", "Documentos regulatorios", "Ficha técnica, inserto, rotulados, certificados, cargos y comunicaciones.", "Regulatorio gobierna documentos del producto y expediente.", ["Adjuntar documento", "Versionar referencia", "Vincular expediente", "Registrar aprobación"], ["No administra manuales SGI", "No reemplaza QMS"], "/admin/regulatorio/documentoregulatorioproducto/"),
        sm("observaciones-autoridad", "Observaciones de autoridad", "Registro de observaciones emitidas por autoridad sanitaria.", "Controla fecha, contenido, vencimiento de respuesta y estado de atención.", ["Registrar observación", "Adjuntar cargo", "Definir fecha límite", "Marcar respuesta"], ["No cierra desviaciones", "No sustituye la respuesta técnica"], "/admin/regulatorio/observacionautoridad/"),
        sm("subsanaciones", "Subsanaciones", "Gestión de respuestas a observaciones regulatorias.", "Evidencia la respuesta presentada y su trazabilidad.", ["Crear subsanación", "Adjuntar sustento", "Registrar presentación", "Vincular observación"], ["No elimina observación original", "No reemplaza comunicación oficial"], "/admin/regulatorio/subsanacionregulatoria/"),
        sm("alertas-regulatorias", "Alertas regulatorias", "Avisos por vencimientos, expedientes y documentos pendientes.", "Reduce riesgo de vencimiento o incumplimiento regulatorio.", ["Configurar alerta", "Notificar responsable", "Escalar riesgo", "Dar seguimiento"], ["No cierra trámites automáticamente", "No reemplaza decisión regulatoria"], "/admin/core/notificacion/"),
    ],
    "qms": [
        sm("documentos-sgi", "Documentos del SGI", "Manuales, procedimientos, instructivos, formatos, registros internos, programas, planes y matrices.", "QMS gobierna documentos del Sistema de Gestión Integrado.", ["Crear documento", "Versionar", "Aprobar", "Declarar vigencia"], ["No administra documentos regulatorios del producto", "No crea productos"], "/admin/qms/documentocontrolado/"),
        sm("lista-maestra", "Lista maestra documental", "Control central de documentos vigentes y obsoletos del SGI.", "Permite trazabilidad de código, versión, estado, responsable y vigencia.", ["Consultar vigencia", "Filtrar estado", "Revisar historial", "Controlar obsoleto"], ["No duplica documentos regulatorios", "No reemplaza repositorio externo"], "/admin/qms/documentocontrolado/"),
        sm("auditorias", "Auditorías", "Planificación y seguimiento de auditorías internas, externas o regulatorias.", "Origina hallazgos y evidencias de calidad cuando corresponda.", ["Planificar auditoría", "Registrar evidencia", "Identificar hallazgos", "Escalar desviación"], ["No reemplaza autoridad sanitaria", "No cierra CAPA sin eficacia"], "/admin/qms/"),
        sm("hallazgos", "Hallazgos", "Registro de incumplimientos, oportunidades de mejora u observaciones internas.", "Puede originar desviaciones, acciones o necesidades de cambio.", ["Registrar hallazgo", "Clasificar severidad", "Asignar responsable", "Vincular evidencia"], ["No es CAPA automática", "No reemplaza investigación"], "/admin/qms/desviacion/"),
        sm("desviaciones", "Desviaciones", "Gestión de desviaciones originadas en QMS, Regulatorio, BPA, BPDT o BPFV.", "Centraliza investigación, trazabilidad y decisión de calidad.", ["Crear desviación", "Investigar", "Vincular producto si aplica", "Cerrar"], ["No modifica producto regulatorio", "No reemplaza lote BPA"], "/admin/qms/desviacion/"),
        sm("capa", "CAPA", "Acciones correctivas y preventivas centralizadas en QMS.", "Toda CAPA pertenece a Calidad/QMS.", ["Crear CAPA", "Asignar responsable", "Verificar eficacia", "Cerrar"], ["No pertenece a BPA", "No pertenece a BPFV", "No pertenece a Regulatorio"], "/admin/qms/capa/"),
        sm("riesgos", "Riesgos", "Identificación y tratamiento de riesgos de calidad.", "Soporta priorización preventiva y mejora continua.", ["Registrar riesgo", "Valorar impacto", "Definir control", "Monitorear"], ["No reemplaza matriz corporativa externa", "No modifica registro sanitario"], "/admin/qms/"),
        sm("control-cambios", "Control de cambios", "Evaluación de cambios internos con impacto en calidad, procesos o cumplimiento.", "Puede relacionarse con Regulatorio si el cambio impacta producto o expediente.", ["Registrar cambio", "Evaluar impacto", "Aprobar", "Verificar implementación"], ["No reemplaza trámite regulatorio", "No actualiza producto sin Regulatorio"], "/admin/qms/"),
        sm("capacitaciones", "Capacitaciones", "Gestión de formación, competencias y evidencias de entrenamiento.", "Asegura conocimiento de procedimientos y buenas prácticas.", ["Crear programa", "Registrar asistencia", "Adjuntar evidencia", "Evaluar eficacia"], ["No reemplaza RR.HH.", "No cierra CAPA por sí sola"], "/admin/qms/"),
        sm("indicadores", "Indicadores de calidad", "Seguimiento de KPIs de calidad, CAPA, desviaciones y cumplimiento.", "Permite revisar tendencias y priorizar mejora continua.", ["Crear indicador", "Actualizar valor", "Analizar tendencia", "Reportar"], ["No reemplaza BI corporativo", "No modifica datos fuente"], "/admin/qms/"),
    ],
    "bpa": [
        sm("almacenes", "Almacenes regulados", "Registro de almacenes bajo Buenas Prácticas de Almacenamiento.", "Controla el espacio regulado sin convertirse en WMS.", ["Crear almacén", "Asignar responsable", "Activar", "Adjuntar evidencia"], ["No gestiona inventario operativo", "No calcula productividad"], "/admin/bpa/almacenregulado/"),
        sm("zonas", "Zonas reguladas", "Cuarentena, aprobado, rechazado, devolución u otras zonas reguladas.", "Permite controlar ubicación regulatoria de lotes sin rack/bin operativo.", ["Crear zona", "Clasificar tipo", "Vincular almacén", "Controlar estado"], ["No maneja ubicaciones rack/bin", "No realiza picking"], "/admin/bpa/zonaregulada/"),
        sm("lotes-bpa", "Lotes BPA", "Registro transaccional/regulatorio de lotes para control BPA.", "Asocia lote a producto regulatorio, vencimiento, estado y evidencia.", ["Registrar lote", "Actualizar estado", "Vincular evidencia", "Consultar por producto"], ["No es maestro general de lotes", "No modifica producto regulatorio"], "/admin/bpa/lotebpa/"),
        sm("cuarentena-liberacion", "Cuarentena y liberación", "Control de estados regulatorios de lotes.", "Gestiona cuarentena, liberado, observado, bloqueado, rechazado o devuelto.", ["Registrar cuarentena", "Liberar", "Bloquear", "Rechazar"], ["No reemplaza ERP", "No gestiona stock valorizado"], "/admin/bpa/lotebpa/"),
        sm("condiciones-ambientales", "Condiciones ambientales", "Seguimiento de temperatura y humedad del almacenamiento.", "Asegura evidencia regulatoria de conservación.", ["Registrar lectura", "Adjuntar evidencia", "Revisar tendencia", "Escalar excursión"], ["No es SCADA", "No reemplaza sensor externo"], "/admin/bpa/"),
        sm("excursiones", "Excursiones BPA", "Registro de desviaciones ambientales o de conservación.", "Permite vincular excursión con lote, almacén y desviación QMS.", ["Crear excursión", "Definir periodo", "Vincular lote", "Escalar a QMS"], ["No cierra CAPA", "No modifica caso BPFV"], "/admin/bpa/excursionbpa/"),
        sm("limpieza", "Limpieza", "Evidencia de limpieza de áreas reguladas.", "Controla cumplimiento BPA sin convertir el módulo en mantenimiento operativo.", ["Registrar actividad", "Adjuntar evidencia", "Asignar responsable", "Verificar cumplimiento"], ["No es módulo de facilities", "No gestiona personal operativo"], "/admin/bpa/"),
        sm("plagas", "Control de plagas", "Seguimiento de controles y evidencias de plagas.", "Mantiene evidencia regulatoria de prevención y control.", ["Registrar control", "Adjuntar certificado", "Reportar hallazgo", "Escalar desviación"], ["No reemplaza proveedor externo", "No cierra CAPA"], "/admin/bpa/"),
        sm("equipos", "Equipos críticos", "Control de equipos críticos asociados al almacenamiento regulado.", "Permite identificar equipos que impactan conservación o cumplimiento.", ["Registrar equipo", "Definir criticidad", "Vincular almacén", "Controlar estado"], ["No es CMMS completo", "No gestiona repuestos"], "/admin/bpa/"),
        sm("mantenimiento-calibracion", "Mantenimiento y calibración", "Evidencias de mantenimiento y calibración de equipos críticos.", "Soporta cumplimiento BPA mediante evidencia documentada.", ["Registrar mantenimiento", "Registrar calibración", "Adjuntar certificado", "Escalar vencimiento"], ["No calcula costos de mantenimiento", "No gestiona órdenes técnicas"], "/admin/bpa/"),
    ],
    "bpdt": [
        sm("transportistas", "Transportistas autorizados", "Registro de empresas transportistas autorizadas.", "Controla elegibilidad regulatoria del transportista.", ["Registrar transportista", "Validar autorización", "Actualizar contacto", "Inactivar"], ["No calcula fletes", "No gestiona contratos completos"], "/admin/bpdt/transportista/"),
        sm("vehiculos", "Vehículos autorizados", "Registro de vehículos aptos para distribución regulada.", "Controla placa, tipo, capacidad referencial y autorización.", ["Registrar vehículo", "Vincular transportista", "Validar estado", "Inactivar"], ["No gestiona flota completa", "No controla combustible"], "/admin/bpdt/vehiculoautorizado/"),
        sm("conductores", "Conductores", "Control documental de conductores si aplica al proceso.", "Permite evidenciar autorización o competencia cuando sea necesario.", ["Registrar conductor", "Adjuntar documento", "Verificar vigencia", "Actualizar estado"], ["No reemplaza RR.HH.", "No controla jornada"], "/admin/bpdt/"),
        sm("documentacion-transporte", "Documentación de transporte", "Evidencias y documentos del traslado regulado.", "Sustenta cumplimiento de conservación, entrega y trazabilidad.", ["Adjuntar documento", "Vincular envío", "Revisar evidencia", "Registrar observación"], ["No reemplaza TMS", "No emite guía logística"], "/admin/bpdt/"),
        sm("conservacion-transito", "Conservación en tránsito", "Control de condiciones de conservación durante transporte.", "Permite evidenciar cumplimiento de condiciones aprobadas.", ["Registrar condición", "Adjuntar registro", "Revisar excursión", "Escalar incidente"], ["No es monitoreo GPS en tiempo real", "No reemplaza data logger"], "/admin/bpdt/"),
        sm("excursiones-transporte", "Excursiones en transporte", "Eventos de temperatura o conservación fuera de condición.", "Se gestionan como incidentes con posible derivación a QMS.", ["Registrar excursión", "Vincular producto", "Adjuntar evidencia", "Escalar desviación"], ["No cierra CAPA", "No libera lote"], "/admin/bpdt/incidentetransporte/"),
        sm("incidentes", "Incidentes BPDT", "Incidentes, devoluciones o entregas fallidas con impacto en calidad.", "Permite trazabilidad y derivación a QMS si corresponde.", ["Crear incidente", "Clasificar tipo", "Vincular vehículo", "Vincular desviación"], ["No planifica rutas", "No asigna vehículos automáticamente"], "/admin/bpdt/incidentetransporte/"),
        sm("devoluciones", "Devoluciones", "Control de devoluciones con impacto en calidad o cumplimiento.", "Permite evaluar evidencia y derivar a QMS o BPA.", ["Registrar devolución", "Adjuntar evidencia", "Evaluar impacto", "Escalar"], ["No gestiona nota de crédito", "No actualiza inventario ERP"], "/admin/bpdt/incidentetransporte/"),
        sm("entregas-fallidas", "Entregas fallidas", "Registro de entregas fallidas con posible impacto en conservación.", "Permite documentar causa, evidencia y decisión de calidad.", ["Registrar evento", "Evaluar impacto", "Vincular producto", "Escalar desviación"], ["No reprograma rutas", "No calcula penalidades logísticas"], "/admin/bpdt/incidentetransporte/"),
    ],
    "bpfv": [
        sm("casos", "Casos de farmacovigilancia", "Registro y gestión de casos BPFV.", "Permite documentar evento, producto sospechoso, lote reportado y estado.", ["Crear caso", "Validar datos", "Actualizar estado", "Cerrar caso"], ["No modifica producto", "No edita lote BPA"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("ram", "Sospechas de RAM", "Registro de sospechas de reacciones adversas a medicamentos.", "Clasifica y evalúa eventos sospechosos asociados a producto.", ["Registrar RAM", "Evaluar gravedad", "Vincular producto", "Dar seguimiento"], ["No confirma causalidad automáticamente", "No modifica registro sanitario"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("eventos-adversos", "Eventos adversos", "Gestión de eventos adversos reportados.", "Permite trazabilidad clínica-regulatoria del evento reportado.", ["Registrar evento", "Validar mínimos", "Clasificar gravedad", "Escalar señal"], ["No reemplaza atención médica", "No administra producto"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("errores-medicacion", "Errores de medicación", "Registro de errores de medicación reportados.", "Permite evaluar impacto, seguimiento y eventual desviación QMS.", ["Registrar error", "Clasificar tipo", "Evaluar impacto", "Vincular desviación"], ["No sanciona personal", "No modifica ficha técnica"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("falta-eficacia", "Falta de eficacia", "Gestión de reportes de falta de eficacia.", "Permite registrar sospecha, producto, lote y seguimiento.", ["Registrar sospecha", "Vincular lote", "Solicitar seguimiento", "Evaluar causalidad"], ["No bloquea lote automáticamente", "No reemplaza investigación QMS"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("causalidad-gravedad", "Causalidad y gravedad", "Evaluación de causalidad, gravedad y clasificación del caso.", "Soporta priorización y cumplimiento regulatorio BPFV.", ["Evaluar gravedad", "Registrar causalidad", "Actualizar estado", "Documentar criterio"], ["No genera CAPA automáticamente", "No reemplaza comité"], "/admin/bpfv/casofarmacovigilancia/"),
        sm("seguimiento", "Seguimiento de caso", "Registro de comunicaciones y ampliaciones de información.", "Mantiene historial del caso y evidencia de seguimiento.", ["Crear seguimiento", "Adjuntar archivo", "Asignar responsable", "Actualizar caso"], ["No borra evento inicial", "No modifica lote BPA"], "/admin/bpfv/seguimientocaso/"),
        sm("consulta-lotes", "Consulta de lotes BPA", "Búsqueda de lotes BPA por producto, número de lote y vencimiento.", "Permite vincular lote existente o marcar lote no encontrado.", ["Buscar lote", "Vincular caso", "Marcar no encontrado", "Consultar estado"], ["No edita estado del lote", "No crea maestro general de lotes"], "/admin/bpa/lotebpa/"),
        sm("senales", "Señales de seguridad", "Identificación y seguimiento de señales potenciales.", "Permite escalar patrones relevantes a evaluación formal.", ["Registrar señal", "Agrupar casos", "Evaluar tendencia", "Escalar comité"], ["No cambia registro sanitario", "No cierra CAPA"], "/admin/bpfv/"),
        sm("reportes-regulatorios", "Reportes regulatorios", "Preparación y control de reportes a autoridad cuando aplique.", "Mantiene trazabilidad de reportabilidad, fechas y sustento.", ["Preparar reporte", "Registrar envío", "Adjuntar acuse", "Controlar plazo"], ["No reemplaza portal de autoridad", "No inventa información clínica"], "/admin/bpfv/"),
        sm("comite-bpfv", "Comité BPFV", "Seguimiento de acuerdos y evaluaciones del comité de farmacovigilancia.", "Evidencia decisiones, responsables y acciones derivadas.", ["Registrar sesión", "Documentar acuerdo", "Asignar responsable", "Dar seguimiento"], ["No reemplaza CAPA QMS", "No modifica producto"], "/admin/bpfv/"),
    ],
}
