SUBMODULES = {
    "core": [
        {
            "slug": "usuarios-perfiles",
            "nombre": "Usuarios y perfiles",
            "descripcion": "Administración de usuarios, perfiles funcionales, empresa asociada, cargos y estado de acceso.",
            "alcance": "Core gestiona identidad y acceso común para toda la suite.",
            "acciones": ["Crear y mantener usuarios", "Asignar empresa y datos de contacto", "Activar o desactivar cuentas"],
            "exclusiones": ["No reemplaza políticas corporativas de RR.HH.", "No duplica roles por módulo sin gobierno central"],
            "admin_url": "/admin/core/usuario/",
        },
        {
            "slug": "roles-permisos",
            "nombre": "Roles y permisos",
            "descripcion": "Control de permisos por perfil, módulo y nivel de responsabilidad del usuario.",
            "alcance": "Asegura segregación de funciones y acceso controlado a registros regulatorios.",
            "acciones": ["Definir grupos", "Asignar permisos", "Controlar acceso por responsabilidad"],
            "exclusiones": ["No crear permisos aislados sin trazabilidad", "No dejar módulos sin control de rol"],
            "admin_url": "/admin/auth/group/",
        },
        {
            "slug": "maestro-productos",
            "nombre": "Maestro de productos",
            "descripcion": "Dato maestro común de productos usado por QMS, BPA, BPDT y BPFV.",
            "alcance": "Centraliza código, nombre comercial, principio activo, forma farmacéutica, concentración, presentación, titular, fabricante, país y estado.",
            "acciones": ["Registrar producto", "Actualizar estado", "Consultar trazabilidad transversal"],
            "exclusiones": ["No administra lotes como maestro general", "No reemplaza ERP de inventario"],
            "admin_url": "/admin/core/producto/",
        },
        {
            "slug": "bitacora-adjuntos",
            "nombre": "Bitácora y adjuntos",
            "descripcion": "Soporte transversal para evidencia, archivos y trazabilidad de registros.",
            "alcance": "Permite adjuntar evidencia y mantener rastro de información crítica.",
            "acciones": ["Registrar evidencia", "Consultar adjuntos", "Mantener trazabilidad"],
            "exclusiones": ["No duplica documentos controlados de QMS", "No sustituye control documental"],
            "admin_url": "/admin/core/archivoadjunto/",
        },
    ],
    "qms": [
        {
            "slug": "gestion-documental",
            "nombre": "Gestión documental",
            "descripcion": "Control documental transversal: código, versión, estado, responsable, vigencia, aprobaciones, historial y archivo.",
            "alcance": "QMS gobierna todos los documentos controlados de la suite.",
            "acciones": ["Crear documento controlado", "Gestionar versión y vigencia", "Mantener lista maestra"],
            "exclusiones": ["No duplicar documentos en BPA, BPDT o BPFV", "No usar adjuntos como documento controlado sin versión"],
            "admin_url": "/admin/qms/documentocontrolado/",
        },
        {
            "slug": "registros-sanitarios",
            "nombre": "Registros sanitarios y documentos regulatorios",
            "descripcion": "Gestión de registros sanitarios, fichas técnicas, insertos, rotulados y condiciones aprobadas.",
            "alcance": "QMS administra vigencia, versión y aprobación documental de información regulatoria de producto.",
            "acciones": ["Registrar número sanitario", "Vincular documento controlado", "Consultar vigencia y condiciones aprobadas"],
            "exclusiones": ["BPA, BPDT y BPFV solo consultan esta información", "No administrar estos documentos desde BPFV"],
            "admin_url": "/admin/qms/registrosanitario/",
        },
        {
            "slug": "desviaciones-hallazgos",
            "nombre": "Desviaciones y hallazgos",
            "descripcion": "Registro y seguimiento de desviaciones originadas en Calidad, BPA, BPDT o BPFV.",
            "alcance": "Centraliza investigación, clasificación y estado de desviaciones.",
            "acciones": ["Registrar desviación", "Clasificar origen", "Cerrar investigación"],
            "exclusiones": ["No crear desviaciones independientes por módulo", "No cerrar hallazgos sin evidencia"],
            "admin_url": "/admin/qms/desviacion/",
        },
        {
            "slug": "capa",
            "nombre": "CAPA centralizada",
            "descripcion": "Gestión única de acciones correctivas y preventivas, verificación de eficacia y cierre.",
            "alcance": "Todas las CAPA pertenecen a QMS, aunque se originen desde BPA, BPDT o BPFV.",
            "acciones": ["Crear CAPA", "Asignar responsable", "Verificar eficacia", "Cerrar CAPA"],
            "exclusiones": ["No crear CAPA por módulo", "No cerrar CAPA sin verificación de eficacia"],
            "admin_url": "/admin/qms/capa/",
        },
        {
            "slug": "riesgos-capacitaciones",
            "nombre": "Riesgos, cambios y capacitaciones",
            "descripcion": "Bloque rector para gestión de riesgos, control de cambios, capacitaciones y mejora continua.",
            "alcance": "Estructura el seguimiento de calidad más allá del evento puntual.",
            "acciones": ["Evaluar riesgo", "Controlar cambios", "Planificar capacitación", "Medir eficacia"],
            "exclusiones": ["No convertir capacitaciones en documentos no controlados", "No separar riesgos por módulo sin consolidación QMS"],
            "admin_url": "/admin/qms/",
        },
    ],
    "bpa": [
        {
            "slug": "almacenes-zonas",
            "nombre": "Almacenes y zonas reguladas",
            "descripcion": "Registro de almacenes, zonas de cuarentena, aprobado, rechazado, devolución u otras zonas reguladas.",
            "alcance": "BPA controla el cumplimiento regulatorio del almacenamiento, no la operación WMS.",
            "acciones": ["Registrar almacén regulado", "Definir zona regulada", "Asignar responsable"],
            "exclusiones": ["No picking", "No packing", "No rack/bin", "No kardex operativo"],
            "admin_url": "/admin/bpa/almacenregulado/",
        },
        {
            "slug": "lotes-bpa",
            "nombre": "Lotes BPA regulatorios",
            "descripcion": "Registro transaccional de lotes cuando requieren control BPA, liberación, observación, bloqueo, rechazo o devolución.",
            "alcance": "El lote no es maestro general; se registra por necesidad regulatoria y trazabilidad BPA.",
            "acciones": ["Registrar lote BPA", "Actualizar estado regulatorio", "Adjuntar evidencia", "Registrar motivo del cambio"],
            "exclusiones": ["No inventario operativo", "No conteo cíclico", "No reposición", "No productividad de almacén"],
            "admin_url": "/admin/bpa/lotebpa/",
        },
        {
            "slug": "excursiones-ambientales",
            "nombre": "Excursiones ambientales",
            "descripcion": "Registro de excursiones de temperatura o humedad con evidencia y posible derivación a QMS.",
            "alcance": "Controla incumplimientos ambientales con impacto regulatorio.",
            "acciones": ["Registrar excursión", "Vincular lote si aplica", "Derivar desviación QMS"],
            "exclusiones": ["No reemplaza sensores en tiempo real", "No automatiza operación de almacén"],
            "admin_url": "/admin/bpa/excursionbpa/",
        },
        {
            "slug": "limpieza-plagas-equipos",
            "nombre": "Limpieza, plagas y equipos críticos",
            "descripcion": "Control de evidencias de limpieza, control de plagas, mantenimiento y calibración de equipos críticos.",
            "alcance": "Soporta cumplimiento BPA mediante registros y evidencias verificables.",
            "acciones": ["Registrar evidencia", "Controlar actividad", "Derivar incumplimiento a QMS"],
            "exclusiones": ["No gestiona órdenes técnicas operativas complejas", "No reemplaza software de mantenimiento industrial"],
            "admin_url": "/admin/bpa/",
        },
    ],
    "bpdt": [
        {
            "slug": "transportistas-vehiculos",
            "nombre": "Transportistas y vehículos autorizados",
            "descripcion": "Registro y control de transportistas, vehículos y conductores cuando aplique.",
            "alcance": "BPDT controla autorización regulatoria, no administración completa de flota.",
            "acciones": ["Registrar transportista", "Autorizar vehículo", "Consultar estado"],
            "exclusiones": ["No cálculo de fletes", "No combustible", "No planificación de flota"],
            "admin_url": "/admin/bpdt/transportista/",
        },
        {
            "slug": "documentacion-transporte",
            "nombre": "Documentación de transporte",
            "descripcion": "Control documental y evidencias asociadas al transporte desde enfoque regulatorio.",
            "alcance": "Mantiene evidencia BPDT sin duplicar control documental de QMS.",
            "acciones": ["Adjuntar evidencia", "Verificar documentación", "Derivar incumplimiento"],
            "exclusiones": ["No TMS", "No asignación automática de vehículos", "No liquidación de transportistas"],
            "admin_url": "/admin/bpdt/",
        },
        {
            "slug": "condiciones-transito",
            "nombre": "Condiciones de conservación en tránsito",
            "descripcion": "Seguimiento regulatorio de condiciones de conservación, excursiones e incidentes en transporte.",
            "alcance": "Controla impacto de calidad durante distribución y transporte.",
            "acciones": ["Registrar incidente", "Vincular producto si aplica", "Derivar desviación QMS"],
            "exclusiones": ["No GPS operativo en tiempo real", "No optimización de rutas"],
            "admin_url": "/admin/bpdt/incidentetransporte/",
        },
        {
            "slug": "devoluciones-entregas-fallidas",
            "nombre": "Devoluciones y entregas fallidas con impacto en calidad",
            "descripcion": "Registro de devoluciones, entregas fallidas e incidentes logísticos relacionados con calidad.",
            "alcance": "Gestiona eventos con relevancia BPDT y derivación a QMS cuando corresponda.",
            "acciones": ["Registrar devolución", "Documentar evidencia", "Escalar incumplimiento"],
            "exclusiones": ["No logística operativa completa", "No planificación de cargas"],
            "admin_url": "/admin/bpdt/incidentetransporte/",
        },
    ],
    "bpfv": [
        {
            "slug": "registro-casos",
            "nombre": "Registro de casos BPFV",
            "descripcion": "Registro inicial de casos, sospechas de RAM, eventos adversos, errores de medicación, falta de eficacia y PRM.",
            "alcance": "Basado en el modelo funcional SIGEFAR-FV, limitado al módulo de farmacovigilancia dentro de la suite.",
            "acciones": ["Registrar caso", "Identificar producto sospechoso", "Registrar lote reportado", "Marcar lote no encontrado si aplica"],
            "exclusiones": ["No administra maestro de productos", "No modifica estados de lotes BPA", "No gestiona CAPA"],
            "admin_url": "/admin/bpfv/casofarmacovigilancia/",
        },
        {
            "slug": "validacion-evaluacion",
            "nombre": "Validación y evaluación del caso",
            "descripcion": "Validación de datos mínimos, gravedad, causalidad y estado del caso.",
            "alcance": "Permite estructurar evaluación BPFV sin duplicar investigación de desviaciones QMS.",
            "acciones": ["Validar datos mínimos", "Evaluar gravedad", "Registrar causalidad", "Cambiar estado del caso"],
            "exclusiones": ["No reemplaza comité QMS", "No cierra desviaciones de calidad"],
            "admin_url": "/admin/bpfv/casofarmacovigilancia/",
        },
        {
            "slug": "seguimiento-casos",
            "nombre": "Seguimiento de casos",
            "descripcion": "Registro de seguimientos, información adicional, evidencias y trazabilidad del caso.",
            "alcance": "Mantiene la historia de seguimiento del caso BPFV.",
            "acciones": ["Registrar seguimiento", "Adjuntar evidencia", "Actualizar información clínica o administrativa"],
            "exclusiones": ["No gestiona documentos controlados", "No reemplaza expediente regulatorio QMS"],
            "admin_url": "/admin/bpfv/seguimientocaso/",
        },
        {
            "slug": "consulta-lotes-bpa",
            "nombre": "Consulta de lotes BPA",
            "descripcion": "Búsqueda y vínculo de lote BPA por producto, número de lote y fecha de vencimiento si aplica.",
            "alcance": "BPFV consulta estado, vencimiento, liberación, bloqueo, rechazo, devolución, excursiones o desviaciones asociadas según permisos.",
            "acciones": ["Buscar lote BPA", "Vincular lote al caso", "Marcar lote no encontrado en BPA"],
            "exclusiones": ["No modifica estado de lote", "No edita registros BPA", "No administra liberación"],
            "admin_url": "/admin/bpa/lotebpa/",
        },
        {
            "slug": "reportes-senales",
            "nombre": "Reportes regulatorios y señales",
            "descripcion": "Base funcional para reportes regulatorios, señales de seguridad, comité de farmacovigilancia e indicadores BPFV.",
            "alcance": "Agrupa análisis BPFV y derivaciones a QMS cuando exista impacto de calidad.",
            "acciones": ["Preparar reporte", "Identificar señal", "Escalar hallazgo o desviación", "Consultar indicadores"],
            "exclusiones": ["No gestiona CAPA", "No reemplaza reportes generales QMS"],
            "admin_url": "/admin/bpfv/",
        },
    ],
}
