VISIBLE_MODULES = [
    {
        "slug": "regulatorio",
        "codigo": "REG",
        "nombre": "SIGEFAR-Regulatorio",
        "titulo": "Registros sanitarios y trámites regulatorios",
        "descripcion": "Gestiona inscripción, renovación, actualizaciones, modificaciones, expedientes, observaciones y alertas regulatorias de productos.",
        "mensaje": "Regulatorio administra el ciclo de vida del registro sanitario y el seguimiento de expedientes ante la autoridad, usando productos de Core y documentos controlados por Calidad.",
        "etiqueta": "Módulo regulatorio",
        "icono": "◉",
        "componentes": [
            "Registros sanitarios",
            "Inscripción de registros",
            "Renovación o reinscripción",
            "Actualizaciones post-registro",
            "Seguimiento de expedientes",
            "Observaciones y subsanaciones",
            "Alertas de vencimiento",
            "Historial regulatorio del producto",
        ],
        "principios": [
            "Gestiona el trámite regulatorio, no el control documental completo",
            "Consulta productos desde Core",
            "Usa documentos controlados por Calidad",
            "Mantiene trazabilidad de expedientes, estados y vencimientos",
        ],
    },
    {
        "slug": "qms",
        "codigo": "QMS",
        "nombre": "SIGEFAR-Calidad",
        "titulo": "Gestión de calidad y cumplimiento documental",
        "descripcion": "Módulo rector de calidad. Centraliza documentos controlados, auditorías, hallazgos, desviaciones, CAPA, riesgos y evidencia para inspecciones regulatorias.",
        "mensaje": "Calidad gobierna documentos, desviaciones, CAPA, riesgos, auditorías, capacitaciones y mejora continua.",
        "etiqueta": "Módulo rector",
        "icono": "✦",
        "componentes": [
            "Documentos controlados",
            "Lista maestra documental",
            "Fichas técnicas, insertos y rotulados",
            "Auditorías y hallazgos",
            "Desviaciones y CAPA",
            "Riesgos y control de cambios",
            "Capacitaciones",
            "Verificación de eficacia",
        ],
        "principios": [
            "Gobierno documental centralizado",
            "CAPA única desde Calidad",
            "Evidencia para auditorías e inspecciones",
            "Mejora continua trazable",
        ],
    },
    {
        "slug": "bpa",
        "codigo": "BPA",
        "nombre": "SIGEFAR-BPA",
        "titulo": "Buenas Prácticas de Almacenamiento",
        "descripcion": "Controla el cumplimiento regulatorio del almacenamiento, condiciones ambientales, evidencias, excursiones y estados regulatorios de lotes.",
        "mensaje": "BPA controla almacenamiento regulatorio y lotes BPA sin convertirse en WMS ni inventario operativo.",
        "etiqueta": "Buenas prácticas",
        "icono": "▣",
        "componentes": [
            "Almacenes y zonas reguladas",
            "Cuarentena, aprobado, rechazado y devoluciones",
            "Temperatura y humedad",
            "Excursiones ambientales",
            "Limpieza y control de plagas",
            "Equipos críticos",
            "Mantenimiento y calibración",
            "Control regulatorio de lotes BPA",
        ],
        "principios": [
            "No es WMS",
            "No maneja picking, packing ni kardex operativo",
            "Deriva incumplimientos a Calidad",
            "Los lotes son transaccionales y regulatorios",
        ],
    },
    {
        "slug": "bpdt",
        "codigo": "BPDT",
        "nombre": "SIGEFAR-BPDT",
        "titulo": "Buenas Prácticas de Distribución y Transporte",
        "descripcion": "Gestiona evidencia regulatoria del transporte, condiciones de conservación en tránsito, incidentes y devoluciones con impacto en calidad.",
        "mensaje": "BPDT controla distribución y transporte regulatorio sin convertirse en TMS ni sistema de planificación logística.",
        "etiqueta": "Buenas prácticas",
        "icono": "⬡",
        "componentes": [
            "Transportistas autorizados",
            "Vehículos autorizados",
            "Conductores, si aplica",
            "Documentación de transporte",
            "Conservación en tránsito",
            "Excursiones e incidentes",
            "Devoluciones",
            "Entregas fallidas con impacto en calidad",
        ],
        "principios": [
            "No es TMS",
            "No optimiza rutas ni calcula fletes",
            "Controla evidencia regulatoria del transporte",
            "Deriva incumplimientos a Calidad",
        ],
    },
    {
        "slug": "bpfv",
        "codigo": "BPFV",
        "nombre": "SIGEFAR-BPFV",
        "titulo": "Farmacovigilancia y BPFV",
        "descripcion": "Permite registrar, evaluar y dar seguimiento a casos de farmacovigilancia, vinculando productos y lotes reportados cuando corresponda.",
        "mensaje": "BPFV gestiona farmacovigilancia y puede consultar lotes BPA vinculados sin modificar su estado regulatorio.",
        "etiqueta": "Farmacovigilancia",
        "icono": "✚",
        "componentes": [
            "Registro de casos",
            "Sospechas de RAM y eventos adversos",
            "Errores de medicación",
            "Falta de eficacia y PRM",
            "Gravedad y causalidad",
            "Seguimiento",
            "Reportes regulatorios",
            "Consulta de lotes BPA",
        ],
        "principios": [
            "No administra productos ni documentos regulatorios",
            "No modifica estados de lotes BPA",
            "Puede registrar lote no encontrado en BPA",
            "Escala hallazgos a Calidad cuando corresponda",
        ],
    },
]

PRINCIPLES = [
    {"titulo": "Trazabilidad", "descripcion": "Toda acción relevante queda registrada para auditoría y revisión posterior.", "icono": "⌁"},
    {"titulo": "Control documental", "descripcion": "Los documentos críticos mantienen versión, vigencia, aprobación, historial y responsable desde Calidad.", "icono": "☷"},
    {"titulo": "Seguridad por roles", "descripcion": "Cada usuario accede solo a funciones y registros autorizados por su perfil.", "icono": "◉"},
    {"titulo": "Evidencia regulatoria", "descripcion": "Los registros sustentan trámites, auditorías, inspecciones y seguimiento interno.", "icono": "✓"},
]

FLOW_STEPS = [
    "Producto maestro en Core",
    "Registro sanitario y trámite regulatorio",
    "Documentos controlados por Calidad",
    "BPA / BPDT / BPFV ejecutan controles",
    "Hallazgos, incidentes o señales",
    "Calidad gestiona CAPA y cierre eficaz",
]

SUBMODULES = {
    "regulatorio": [
        {"slug": "registros-sanitarios", "nombre": "Registros sanitarios", "descripcion": "Maestro regulatorio de registros sanitarios por producto, titular, fabricante, país, vigencia y estado.", "alcance": "Consolida datos regulatorios del registro sanitario sin reemplazar el maestro de productos de Core.", "acciones": ["Registrar número sanitario", "Vincular producto", "Controlar vigencia", "Consultar estado regulatorio"], "exclusiones": ["No administra documentos controlados", "No reemplaza Core", "No gestiona CAPA"], "admin_url": "/admin/qms/registrosanitario/"},
        {"slug": "inscripcion", "nombre": "Inscripción de registro", "descripcion": "Gestión del expediente nuevo para obtener un registro sanitario.", "alcance": "Controla preparación, presentación, seguimiento y resultado del trámite de inscripción.", "acciones": ["Crear expediente", "Registrar fecha de presentación", "Controlar estado", "Registrar resolución final"], "exclusiones": ["No duplica documentos QMS", "No reemplaza mesa de partes externa"], "admin_url": "/admin/qms/registrosanitario/"},
        {"slug": "renovacion", "nombre": "Renovación o reinscripción", "descripcion": "Seguimiento de renovación, alertas de vencimiento y control del expediente de reinscripción.", "alcance": "Evita vencimientos no controlados y mantiene trazabilidad del trámite de renovación.", "acciones": ["Generar alerta", "Registrar expediente", "Controlar hitos", "Actualizar vigencia"], "exclusiones": ["No cambia documentos sin control QMS", "No cierra observaciones sin evidencia"], "admin_url": "/admin/qms/registrosanitario/"},
        {"slug": "actualizaciones", "nombre": "Actualizaciones y modificaciones", "descripcion": "Cambios post-registro: titular, fabricante, fórmula, especificaciones, presentación, rotulado, inserto o ficha técnica.", "alcance": "Controla solicitudes de modificación y su impacto regulatorio-documental.", "acciones": ["Registrar tipo de cambio", "Vincular documentos soporte", "Controlar aprobación", "Actualizar historial"], "exclusiones": ["No aprueba documentos fuera de QMS", "No modifica producto maestro sin control"], "admin_url": "/admin/qms/controldecambio/"},
        {"slug": "expedientes", "nombre": "Seguimiento de expedientes", "descripcion": "Control de número de expediente, autoridad, etapa, observaciones, subsanaciones y resultado.", "alcance": "Da trazabilidad administrativa y regulatoria del trámite ante la autoridad.", "acciones": ["Registrar expediente", "Actualizar etapa", "Registrar observación", "Registrar subsanación"], "exclusiones": ["No sustituye portal de la autoridad", "No elimina necesidad de evidencia adjunta"], "admin_url": "/admin/qms/"},
        {"slug": "alertas", "nombre": "Alertas regulatorias", "descripcion": "Alertas por vencimientos, trámites próximos, documentos pendientes y registros en riesgo.", "alcance": "Prioriza seguimiento regulatorio y reduce riesgo de vencimiento o incumplimiento.", "acciones": ["Configurar alerta", "Visualizar vencimientos", "Escalar riesgo", "Notificar responsable"], "exclusiones": ["No reemplaza la decisión regulatoria", "No cierra trámites automáticamente"], "admin_url": "/admin/core/notificacion/"},
    ],
    "qms": [],
    "bpa": [],
    "bpdt": [],
    "bpfv": [],
}
