VISIBLE_MODULES = [
    {
        "slug": "core",
        "codigo": "CORE",
        "nombre": "SIGEFAR-Core",
        "titulo": "Núcleo común de la plataforma",
        "descripcion": "Administra empresas, usuarios, cargos, roles, permisos, autenticación, seguridad, bitácora, licenciamiento, adjuntos, notificaciones y parámetros generales.",
        "mensaje": "Core sostiene la suite y provee servicios transversales, sin administrar productos regulatorios, documentos regulatorios, CAPA, lotes ni procesos operativos.",
        "etiqueta": "Núcleo común",
        "icono": "◆",
        "componentes": [
            "Empresas y usuarios",
            "Cargos, roles y permisos",
            "Autenticación y seguridad",
            "Bitácora general",
            "Licenciamiento modular",
            "Adjuntos transversales",
            "Notificaciones",
            "Parámetros generales",
        ],
        "principios": [
            "Sostiene la suite completa",
            "No se vende como módulo independiente",
            "No administra productos regulatorios",
            "Garantiza seguridad y trazabilidad transversal",
        ],
    },
    {
        "slug": "regulatorio",
        "codigo": "REG",
        "nombre": "SIGEFAR-Regulatorio",
        "titulo": "Gestión regulatoria integral del producto",
        "descripcion": "Crea y gobierna el producto regulatorio, expedientes DIGEMID, registros sanitarios, trámites, observaciones, subsanaciones y documentos regulatorios del producto.",
        "mensaje": "Regulatorio es dueño funcional del producto regulatorio y de su ciclo de vida ante la autoridad sanitaria.",
        "etiqueta": "Módulo regulatorio",
        "icono": "◉",
        "componentes": [
            "Productos regulatorios",
            "Expedientes DIGEMID",
            "Registros sanitarios",
            "Inscripción y renovación",
            "Modificaciones post-registro",
            "Documentos regulatorios del producto",
            "Observaciones y subsanaciones",
            "Alertas de vencimiento",
        ],
        "principios": [
            "Crea y gobierna productos regulatorios",
            "Administra documentos regulatorios del producto",
            "Mantiene trazabilidad de expedientes y vencimientos",
            "Los demás módulos consultan productos según permisos",
        ],
    },
    {
        "slug": "qms",
        "codigo": "QMS",
        "nombre": "SIGEFAR-Calidad",
        "titulo": "Sistema de Gestión Integrado y calidad",
        "descripcion": "Gestiona documentos del SGI, auditorías, hallazgos, desviaciones, CAPA, riesgos, cambios, capacitaciones, eficacia e indicadores de calidad.",
        "mensaje": "Calidad/QMS gobierna el Sistema de Gestión Integrado y toda CAPA, sin administrar productos ni documentos regulatorios del expediente.",
        "etiqueta": "Módulo rector",
        "icono": "✦",
        "componentes": [
            "Documentos del SGI",
            "Lista maestra documental SGI",
            "Auditorías y hallazgos",
            "Desviaciones y CAPA",
            "Riesgos y control de cambios",
            "Capacitaciones",
            "Verificación de eficacia",
            "Indicadores de calidad",
        ],
        "principios": [
            "Gobierno del Sistema de Gestión Integrado",
            "CAPA única desde Calidad",
            "No administra documentos regulatorios del producto",
            "Mejora continua trazable",
        ],
    },
    {
        "slug": "bpa",
        "codigo": "BPA",
        "nombre": "SIGEFAR-BPA",
        "titulo": "Buenas Prácticas de Almacenamiento",
        "descripcion": "Controla el cumplimiento regulatorio del almacenamiento, condiciones ambientales, evidencias, excursiones y estados regulatorios de lotes.",
        "mensaje": "BPA controla almacenamiento regulatorio y lotes BPA sin convertirse en WMS ni inventario operativo.",
        "etiqueta": "Buenas prácticas",
        "icono": "▣",
        "componentes": [
            "Almacenes y zonas reguladas",
            "Cuarentena, aprobado, rechazado y devoluciones",
            "Temperatura y humedad",
            "Excursiones ambientales",
            "Limpieza y control de plagas",
            "Equipos críticos",
            "Mantenimiento y calibración",
            "Control regulatorio de lotes BPA",
        ],
        "principios": [
            "No es WMS",
            "Consulta productos desde Regulatorio",
            "Deriva incumplimientos a Calidad",
            "Los lotes son transaccionales y regulatorios",
        ],
    },
    {
        "slug": "bpdt",
        "codigo": "BPDT",
        "nombre": "SIGEFAR-BPDT",
        "titulo": "Buenas Prácticas de Distribución y Transporte",
        "descripcion": "Gestiona evidencia regulatoria del transporte, condiciones de conservación en tránsito, incidentes y devoluciones con impacto en calidad.",
        "mensaje": "BPDT controla distribución y transporte regulatorio sin convertirse en TMS ni sistema de planificación logística.",
        "etiqueta": "Buenas prácticas",
        "icono": "⬡",
        "componentes": [
            "Transportistas autorizados",
            "Vehículos autorizados",
            "Conductores, si aplica",
            "Documentación de transporte",
            "Conservación en tránsito",
            "Excursiones e incidentes",
            "Devoluciones",
            "Entregas fallidas con impacto en calidad",
        ],
        "principios": [
            "No es TMS",
            "Consulta productos desde Regulatorio",
            "Controla evidencia regulatoria del transporte",
            "Deriva incumplimientos a Calidad",
        ],
    },
    {
        "slug": "bpfv",
        "codigo": "BPFV",
        "nombre": "SIGEFAR-BPFV",
        "titulo": "Farmacovigilancia y BPFV",
        "descripcion": "Permite registrar, evaluar y dar seguimiento a casos de farmacovigilancia, vinculando productos regulatorios y lotes reportados cuando corresponda.",
        "mensaje": "BPFV gestiona farmacovigilancia y puede consultar lotes BPA vinculados sin modificar su estado regulatorio.",
        "etiqueta": "Farmacovigilancia",
        "icono": "✚",
        "componentes": [
            "Registro de casos",
            "Sospechas de RAM y eventos adversos",
            "Errores de medicación",
            "Falta de eficacia y PRM",
            "Gravedad y causalidad",
            "Seguimiento",
            "Reportes regulatorios",
            "Consulta de lotes BPA",
        ],
        "principios": [
            "No administra productos regulatorios",
            "No modifica estados de lotes BPA",
            "Puede registrar lote no encontrado en BPA",
            "Escala hallazgos a Calidad cuando corresponda",
        ],
    },
]

PRINCIPLES = [
    {"titulo": "Trazabilidad", "descripcion": "Toda acción relevante queda registrada para auditoría y revisión posterior.", "icono": "⌁"},
    {"titulo": "Gobierno documental distribuido", "descripcion": "Regulatorio gobierna documentos regulatorios del producto; QMS gobierna documentos del SGI.", "icono": "☷"},
    {"titulo": "Seguridad por roles", "descripcion": "Core controla identidad, acceso y permisos para que cada usuario vea solo lo autorizado.", "icono": "◉"},
    {"titulo": "Evidencia regulatoria", "descripcion": "Los registros sustentan trámites, auditorías, inspecciones y seguimiento interno.", "icono": "✓"},
]

FLOW_STEPS = [
    "Core sostiene usuarios, seguridad y licencias",
    "Regulatorio crea producto y expediente",
    "QMS gestiona SGI y CAPA",
    "BPA / BPDT / BPFV consultan producto regulatorio",
    "Hallazgos, incidentes o señales",
    "QMS verifica eficacia y cierre",
]

SUBMODULES = {
    "core": [
        {"slug": "usuarios-perfiles", "nombre": "Usuarios y perfiles", "descripcion": "Gestión de usuarios, nombres, correos, estado y perfil organizacional.", "alcance": "Permite administrar usuarios del sistema como parte del núcleo común.", "acciones": ["Crear usuario", "Editar perfil", "Activar o inactivar", "Asignar datos base"], "exclusiones": ["No reemplaza RR.HH.", "No gestiona CAPA", "No administra expedientes regulatorios"], "admin_url": "/admin/core/usuario/"},
        {"slug": "roles-permisos", "nombre": "Roles y permisos", "descripcion": "Configuración de acceso por rol, funciones y visibilidad por módulo.", "alcance": "Define qué puede ver y hacer cada usuario.", "acciones": ["Asignar rol", "Definir permisos", "Restringir visibilidad", "Controlar acceso"], "exclusiones": ["No administra documentos QMS", "No administra productos regulatorios"], "admin_url": "/admin/auth/group/"},
        {"slug": "licenciamiento", "nombre": "Licenciamiento modular", "descripcion": "Control de módulos habilitados por empresa.", "alcance": "Permite activar módulos sin vender Core como módulo separado.", "acciones": ["Habilitar módulo", "Configurar empresa", "Definir vigencia", "Controlar acceso por licencia"], "exclusiones": ["No vende Core como módulo separado", "No reemplaza gobierno QMS"], "admin_url": "/admin/core/licenciamodulo/"},
        {"slug": "parametros-adjuntos", "nombre": "Parámetros, adjuntos y notificaciones", "descripcion": "Servicios transversales para configuración, archivos y avisos.", "alcance": "Core provee infraestructura común sin gobernar documentos funcionales.", "acciones": ["Definir parámetros", "Subir adjuntos", "Emitir notificaciones", "Registrar trazabilidad"], "exclusiones": ["No gobierna documentos regulatorios", "No gobierna documentos SGI"], "admin_url": "/admin/core/parametrogeneral/"},
    ],
    "regulatorio": [
        {"slug": "productos-regulatorios", "nombre": "Productos regulatorios", "descripcion": "Creación y gobierno del producto regulado vinculado a expediente, registro sanitario y condiciones aprobadas.", "alcance": "Regulatorio es dueño funcional del producto regulatorio.", "acciones": ["Crear producto", "Actualizar datos regulatorios", "Controlar estado", "Consultar historial"], "exclusiones": ["No crea lotes", "No gestiona CAPA"], "admin_url": "/admin/regulatorio/productoregulatorio/"},
        {"slug": "expedientes-digemid", "nombre": "Expedientes DIGEMID", "descripcion": "Control de inscripción, renovación, reinscripción, modificaciones y actualizaciones.", "alcance": "Gestiona trámite, etapa, autoridad, observaciones y resultado.", "acciones": ["Crear expediente", "Registrar presentación", "Actualizar estado", "Registrar resolución"], "exclusiones": ["No reemplaza portal de autoridad", "No cierra CAPA"], "admin_url": "/admin/regulatorio/expedientedigemid/"},
        {"slug": "registros-sanitarios", "nombre": "Registros sanitarios", "descripcion": "Control de número de registro, vigencia, estado y resolución asociada.", "alcance": "Mantiene trazabilidad del registro sanitario del producto.", "acciones": ["Registrar número", "Controlar vencimiento", "Adjuntar resolución", "Actualizar estado"], "exclusiones": ["No duplica producto en Core", "No administra documentos SGI"], "admin_url": "/admin/regulatorio/registrosanitarioregulatorio/"},
        {"slug": "documentos-regulatorios", "nombre": "Documentos regulatorios del producto", "descripcion": "Ficha técnica, inserto, rotulados, condiciones aprobadas, certificados, cargos y comunicaciones de autoridad.", "alcance": "Regulatorio gobierna documentos del expediente y producto.", "acciones": ["Adjuntar documento", "Versionar referencia", "Vincular expediente", "Registrar aprobación"], "exclusiones": ["No administra manuales SGI", "No reemplaza QMS"], "admin_url": "/admin/regulatorio/documentoregulatorioproducto/"},
    ],
    "qms": [],
    "bpa": [],
    "bpdt": [],
    "bpfv": [],
}
