# Generated by Django 5.2.4 on 2026-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('EXCURSION', 'Excursión'), ('INCIDENTE', 'Incidente'), ('DEVOLUCION', 'Devolución'), ('ENTREGA_FALLIDA', 'Entrega fallida')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Incidente BPDT',
                'verbose_name_plural': 'Incidentes BPDT',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('autorizado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('capacidad_referencial', models.CharField(blank=True, max_length=120)),
                ('autorizado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehículo autorizado',
                'verbose_name_plural': 'Vehículos autorizados',
                'ordering': ['placa'],
            },
        ),
    ]
