# Generated by Django 5.2.4 on 2026-06-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpdt', '0001_initial'),
        ('core', '0001_initial'),
        ('qms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentetransporte',
            name='desviacion_qms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_bpdt', to='qms.desviacion'),
        ),
        migrations.AddField(
            model_name='incidentetransporte',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AddField(
            model_name='incidentetransporte',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_bpdt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentetransporte',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='bpdt.transportista'),
        ),
        migrations.AddField(
            model_name='vehiculoautorizado',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='bpdt.transportista'),
        ),
        migrations.AddField(
            model_name='incidentetransporte',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='bpdt.vehiculoautorizado'),
        ),
    ]
