# Generated by Django 5.2.4 on 2026-06-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpdt', '0002_initial'),
        ('regulatorio', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentetransporte',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_bpdt', to='regulatorio.productoregulatorio'),
        ),
    ]
