# Generated by Django 5.2.4 on 2026-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoFarmacovigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('tipo_evento', models.CharField(choices=[('RAM', 'Sospecha de RAM'), ('EVENTO_ADVERSO', 'Evento adverso'), ('ERROR_MEDICACION', 'Error de medicación'), ('FALTA_EFICACIA', 'Falta de eficacia'), ('PRM', 'Problema relacionado con medicamento')], max_length=40)),
                ('numero_lote_reportado', models.CharField(blank=True, max_length=120)),
                ('fecha_vencimiento_reportada', models.DateField(blank=True, null=True)),
                ('lote_no_encontrado_bpa', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('NO_GRAVE', 'No grave'), ('GRAVE', 'Grave'), ('NO_EVALUADA', 'No evaluada')], default='NO_EVALUADA', max_length=20)),
                ('causalidad', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDACION', 'Validación'), ('SEGUIMIENTO', 'Seguimiento'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
            ],
            options={
                'verbose_name': 'Caso de farmacovigilancia',
                'verbose_name_plural': 'Casos de farmacovigilancia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='bpfv/seguimientos/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Seguimiento de caso',
                'verbose_name_plural': 'Seguimientos de casos',
                'ordering': ['-fecha'],
            },
        ),
    ]
