# Generated by Django 5.2.4 on 2026-06-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpa', '0002_initial'),
        ('bpfv', '0001_initial'),
        ('core', '0001_initial'),
        ('qms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casofarmacovigilancia',
            name='desviacion_qms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_bpfv', to='qms.desviacion'),
        ),
        migrations.AddField(
            model_name='casofarmacovigilancia',
            name='lote_bpa_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_bpfv', to='bpa.lotebpa'),
        ),
        migrations.AddField(
            model_name='casofarmacovigilancia',
            name='producto_sospechoso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_bpfv', to='core.producto'),
        ),
        migrations.AddField(
            model_name='casofarmacovigilancia',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_bpfv_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimientocaso',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='bpfv.casofarmacovigilancia'),
        ),
        migrations.AddField(
            model_name='seguimientocaso',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_bpfv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='casofarmacovigilancia',
            index=models.Index(fields=['codigo'], name='bpfv_casofa_codigo_09afe4_idx'),
        ),
        migrations.AddIndex(
            model_name='casofarmacovigilancia',
            index=models.Index(fields=['numero_lote_reportado'], name='bpfv_casofa_numero__e2d727_idx'),
        ),
    ]
