# Generated by Django 5.2.4 on 2026-06-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpfv', '0002_initial'),
        ('regulatorio', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casofarmacovigilancia',
            name='producto_sospechoso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_bpfv', to='regulatorio.productoregulatorio'),
        ),
    ]
